spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:~/test
        driver-class-name: org.h2.Driver
        username: sa
        password:
    # jpa 설정
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            dialect: org.hibernate.dialect.H2Dialect
            show-sql: true
            foramt-sql: true
        # 시작과 종료에서 모두 drop
        hibernate:
            ddl-auto: create-drop

    devtools:
        livereload:
            enabled: true
# mybatis설정
mybatis:
    # classpath는 기본적으로 resources 폴더 생각!
    mapper-locations: classpath:mybatis/mapper/h2/**/**.xml
    type-handlers-package: com.nareun.blog.mapper.typehandler
    type-aliases-package: com.nareun.blog.mapper.model
    configuration:
        map-underscore-to-camel-case: true
        default-statement-timeout: 30
        default-fetch-size: 100
