# ! 모든 빌드 프로세스를 docker에서 
FROM gradle:8.4.0-jdk AS build
WORKDIR /home/app
COPY . /home/app/
RUN gradle clean build --no-daemon

# ~> 새 이미지를 사용하는 이유는 저장소 이미지에는 openjdk이외에도 많은 것들이 담겨 있어서
# ~> 컨테이너 실행 시 가급적 작은 이미지를 사용하자
FROM openjdk:18.0-slim
EXPOSE 5000
COPY --from=build /home/app/build/libs/*.jar app.jar
ENTRYPOINT [ "sh" , "-c", "java -jar /app.jar"]

#* 이 방법의 문제는 코드가 변경되면 또 다시 빌드하는데 5분정도의 시간이 걸리는 것